---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-app
  labels:
    app: amazon-prime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-prime-app
  template:
    metadata:
      labels:
        app: amazon-prime-app
    spec:
      containers:
      - name: amazon-prime-container
        image: 941377143083.dkr.ecr.ap-south-1.amazonaws.com/amazon-prime:3
        ports:
        - containerPort: 80
...
