---
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-app
  labels:
    app: amazon-prime-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: amazon-prime-app
  type: LoadBalancer
...
